### PR TITLE
Select `wilds` datasets for NLP tools

### LINKED ISSUE #151: Select data for benchmarking
### Task

Select 1+ datasets that can be used as test / example data for NLP-based drift detection methods

### Impact

Helps test other tools / any algorithms developed within `menelaus`

### PR DESCRIPTION
**Pull request by Anmol-Srivastava**
Closes #151 

#### Added

- `wilds` install option
- intermediate example notebook/converted script that downloads, demonstrates 2 `wilds` datasets

#### Changed
- tweaked/removed outdated data generation scripts
- tweaked `.gitignore`

### CODE REVIEW

**Comment by Anmol-Srivastava** [comment]
@tms-bananaquit all ready here, just a precursor to developing NLP detectors

**Review by tms-bananaquit — APPROVED** [review]
Noted these items in #154, for when the example is fleshed out:
- [x] Update README to note the `wilds` setup option
- [ ] Update RTD/TOC to include example?

**Comment by tms-bananaquit** [comment]
The notebook currently downloads to `data\amazon_v2.1\...` if I run it from my default directory; the .gitignore targets `/docs/source/examples/**/data`. Maybe the notebook should be updated to point to that directory?

**Comment by Anmol-Srivastava** [comment]
Updated `README`, the RTD perhaps we save for the example issue.

Clean fix to the download location seemed tricky, so I had the code download to `"./wilds_datasets"` and have the `.gitignore` ignore `"wilds_datasets/"` at any level

**Pull request merged**
