### PR TITLE
84 remove redundant docstrings

### LINKED ISSUE #84: Remove redundant docstrings in child classes
Python 3.5 (and potentially my IDE) fixed the problem I was seeing where inherited docstrings didn't work, so we don't need to dupe them anymore to get proper display in both RTD and an IDE.

- [x] add `"inherited-members": True` to conf.py
- [x] remove attributes inherited from `drift_detector` from each docstring -- double-check that this works properly.
- [ ] remove methods that are _only_ overwriting parent classes for the purposes of the docstring
   - [x] ADWINacc
   - [x] kdq-tree?
   - [x] HDM/HDDDM/CDBD
- [x] remove test_adwin_acc redundant tests (all but the first)
- [x] confirm that the docs build properly and that docstring lookup is functional for child classes

### PR DESCRIPTION
**Pull request by tms-bananaquit**
Fix #84.

We trade "a list of annoying warnings on sphinx-build" for "not having to maintain redundant unit tests or docstrings in child classes." The problem _seems_ to be due to a glitch in sphinx. 

I'll make a subsequent issue with a dump of the errors.

### CODE REVIEW

**Comment by tms-bananaquit** [comment]
I've removed the redundant methods and unit tests from HDDDM, CDBD, and ADWINOutcome.

The attribute docstrings are still redundant, but that's something to do with either sphinx being glitched out, or our setup not being exactly right; in any case, the time tradeoff seems favorable to this change.

**Review by Anmol-Srivastava — APPROVED** [review]
Approved! That `find_git_root` test was bothering me as well.

**Comment by tms-bananaquit** [comment]
Turns out the error messages were because `drift_state` is a property, so it triggers the "this is redundant!" error in a way that the non-property attribs do not. I can remove those, and kill that error.

Going further, we could make properties of `total_*` and `*_since_reset`, so that they'd also be inherited. I guess we could make sure they're always integers when set.

It remains pretty silly that we can't just have sphinx drop the parent's attributes downward, though.

**Comment by tms-bananaquit** [comment]
Flipped all of these to properties and cleaned up the documentation. Adding the `"member-order": "groupwise"` option (NOT the `autodoc_member_order` option) clusters these a little bit better, too.

I think it'd be preferable to have these ~~properties~~ attributes show at the top, instead of the bottom, but this works for now.

Opened #87 to note the problems with this solution.

**Pull request merged**
